name: Compile Sketches

# The workflow will run on every push and pull request to the repository
on:  [push, pull_request]


jobs:
  Compile-Sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v3

      # Standard target Arduino Uno
      - name: Compile sketches for Arduino
        uses: arduino/compile-sketches@v1

      # Second test for ESP specific branches in ESP example
      - name: Compile sketches for ESP32
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          # Compile target ESP32 dev kit
          fqbn: 'esp32:esp32:esp32s3'

      # Third round of tests for ATTiny
      - name: Compile sketches for ATTiny
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: ATTinyCore:avr
              source-url: http://drazzy.com/package_drazzy.com_index.json
          # compile target ATtiny25/45/85 (No bootloader)            
          fqbn: 'ATTinyCore:avr:attinyx5'

