name: Compile Sketches

# The workflow will run on every push and pull request to the repository
on:  [push, pull_request]


jobs:
  Compile-Sketch:
    runs-on: ubuntu-latest

    env:
      # Location of the repository relative to the runner workspace
      REPO_PATH: libraries/pocketBME280
      
    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_PATH }}

      # Standard target Arduino Uno
      - name: Compile sketches for Arduino
        uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-path: ${{ env.REPO_PATH }}
          sketch-paths: |
            ${{ env.REPO_PATH }}/examples/Simple
            ${{ env.REPO_PATH }}/examples/IntMath
            ${{ env.REPO_PATH }}/examples/ESP
      # Second test for ESP specific branches in ESP example
      - name: Compile sketches for ESP32
        uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-path: src
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          # Compile target ESP32 dev kit
          fqbn: 'esp32:esp32:esp32s3'
          sketch-paths: |
            ${{ env.REPO_PATH }}/examples/ESP
      # Third round of tests for ATTiny
      - name: Compile sketches for ATTiny
        uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-path: src
          platforms: |
            - name: ATTinyCore:avr
              source-url: http://drazzy.com/package_drazzy.com_index.json
          # compile target ATtiny25/45/85 (No bootloader)            
          fqbn: 'ATTinyCore:avr:attinyx5'
          sketch-paths: |
            ${{ env.REPO_PATH }}/examples/Simple
            ${{ env.REPO_PATH }}/examples/IntMath
